### ISSUE TITLE
Add VTK output plots

### ISSUE THREAD

**Issue by mvanzulli** [mvanzulli/ONSAS.jl#170]
Looking for previous contributions:
- [x] July (no vtk related features) (https://github.com/ONSAS/ONSAS.jl/tree/2a6ea5950320e0eb121a9f4146d8dec2730a45d8)
- [x] August (no vtk releated features)
https://github.com/ONSAS/ONSAS.jl/tree/f54d01f3ee5c556969370003ea52c07c20bd5114/src
- [x] October (no vtk releated features)   
(https://github.com/ONSAS/ONSAS.jl/tree/e959d4c59a5afd020ed87bee61738b1760a59354/src)
 - [x] November (no vtk releated features)   
 https://github.com/ONSAS/ONSAS.jl/tree/50ebd3713af376d1309d85e721792c7ad965df84
 - [x] December (no vtk releated features)   
 https://github.com/ONSAS/ONSAS.jl/tree/3b4f08ced4a763e0977080d701e7d2ee69140e0e/src
  - [x]  January (no vtk releated features)   
https://github.com/ONSAS/ONSAS.jl/tree/f8ae83369335f241a2e5039a4cc47eba0a988185/src
 
Maybe it was in another ONSAS.jl version @jorgepz ?

**Comment by jorgepz** [comment]
I was probably thinking about this. I thought it was in onsas.jl, thanks for looking it up.

**Comment by jorgepz** [comment]
Anyway these functions are yet to be implemented. Probably not as grids but using the tetrahedron connectivity.
