### ISSUE TITLE
Create `BoundaryConditions` module and interface

### ISSUE THREAD

**Issue by mvanzulli** [mvanzulli/ONSAS.jl#25]
The following boundary conditions structs are included:
- [ ] `AbstractBoundaryCondition`
- [ ] `LoadBoundaryCondition`
- [ ] Tests `LoadsBoundaryCondition`
- [ ] `UserLoadBoundaryCondition`
- [ ] Tests `UserLoadBoundaryCondition`
- [ ] `SpringBoundaryCondition`
- [ ] Tests `SpringBoundaryCondition` 
- [ ] `DisplacementBoundaryCondition`
- [ ] Test `DisplacementBoundaryCondition`

**Comment by jorgepz** [comment]
I would use singular load disp spring instead of plural.
