### ISSUE TITLE
Include a `ONSAS.Utils` module :hammer:

### ISSUE THREAD

**Issue by mvanzulli** [mvanzulli/ONSAS.jl#26]
This module is used to define first methods (which do not belong to a specific module) and then overload them. For instance the `label` method should be defined in:

```julia
module Utils

" Function that returns the label of an object "
function label() end 

end #  module  
```

Then inside the Geometry module it would be used: 

```julia
module BoundaryCondition

@reexport import ..Utils: label

label(bc::AbstractBoundaryCondition) = bc.label 
...
```

The same principle can be applied to Gauss integrations points. This is based on the I of [SOLID](https://en.wikipedia.org/wiki/SOLID) principle

**Comment by jorgepz** [comment]
Naissss 👍🏼
