### ISSUE TITLE
unicode errors in linear extension

### ISSUE THREAD

**Issue by jorgepz** [mvanzulli/ONSAS.jl#343]
I get some unicode errors in Linux, that we checked with @mvanzulli that are related to the browsers and IDEs used.

![image](https://github.com/ONSAS/ONSAS.jl/assets/42485529/cb717ee1-97ff-4eb3-a883-d6a9633d2373)

and running the script:

```julia
julia> include("examples/linear_extension/linear_extension.jl")
ERROR: LoadError: UndefVarError: Lₖ not defined
Stacktrace:
 [1] macro expansion
   @ ~/work/onsas/ONSAS.jl_repo/examples/linear_extension/linear_extension.jl:65 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/Suppressor/tQJeL/src/Suppressor.jl:127 [inlined]
 [3] run_linear_extension_example()
   @ Main ~/work/onsas/ONSAS.jl_repo/examples/linear_extension/linear_extension.jl:64
 [4] top-level scope
   @ ~/work/onsas/ONSAS.jl_repo/examples/linear_extension/linear_extension.jl:196
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [6] top-level scope
   @ REPL[3]:1
in expression starting at /home/jor/work/onsas/ONSAS.jl_repo/examples/linear_extension/linear_extension.jl:196
```

I propose slowly removing unicode characters at least from example scripts so that the code is easier to adopt for non unicode/julia users.

**Comment by mforets** [comment]
While I'm not opposed to changing some subscripts to `Lx` etc, the underlying issue is on the user device (other Julia related functionality will eventually not display properly) -- you may check https://discourse.julialang.org/t/failing-to-show-unicode-character-in-julia-file/55938 on pointers to fix this.

**Comment by jorgepz** [comment]
we discussed this today with @mforets . indeed the error is reproduced also in android devices using chrome, or windows devices using chrome without having VSCode installed. 
we set that the tutorial more basic examples wont have unicode characters in order to avoid this problem in non-vscode beginner level users
