### ISSUE TITLE
Rename `apply` on BC to `fixed_dofs`

### ISSUE THREAD

**Issue by mforets** [mvanzulli/ONSAS.jl#357]
Eg. `apply(bc::FixedDof, n::AbstractNode)` becoming `fixed_dofs` -- I think the second notation is cleaner.

**Comment by mforets** [comment]
Do we generally agree on this?

Ah, I see this mainly works for `bc::FixedDof`..

**Comment by mvanzulli** [comment]
Apply works for all boundary conditions, you suggest only to change the name on the function that fixes `Dof`s ?

**Comment by mvanzulli** [comment]
This is done, `fixed_dofs = apply(bcs, fixed_dof_bcs(bcs))`. Thanks, @mforets, for suggesting this.
