### ISSUE TITLE
Split examples into model and tests

### ISSUE THREAD

**Issue by mforets** [mvanzulli/ONSAS.jl#366]
Split eg. `run_uniaxial_compression()` into two separate functions such that the structure (maybe the analysis) can be obtained independently of the tests.

Files to revamp:

- [x] cantilever.jl
- [x] clamed_truss.jl
- [x] cylinder_internal_pressure.jl
- [x] linear_extension.jl (wait for #414) 
- [x] uniaxial_compression.jl
- [x] von_misses_truss.jl

**Comment by mvanzulli** [comment]
Okay, we can open an issue to implement this function splitting across the examples. Also, there should be two functions to create the structure: manufactured and via Gmsh.

**Comment by mvanzulli** [comment]
This examples revamp should remove sub indexes unicode fonts, as sugested @jorgepz

**Comment by mvanzulli** [comment]
```julia

abstract type AbstractCase end
struct FirstCase <: AbstractCase end
struct SecondCase <: AbstractCase end

....
# Implement solve and test for many cases. Note the cases can dispatch on tests too. 
....


"Run the example"
function run()
    for case in (FirstCase(), SecondCase())
        sol = solve(case)
        test(sol, case)
    end
end
```
