### ISSUE TITLE
Update `SVK` to `Svk` material into examples

### ISSUE THREAD

**Issue by mvanzulli** [mvanzulli/ONSAS.jl#387]

**Comment by mforets** [comment]
Not sure what you have in mind? The patterns

```julia
my_svk_mat = SVK(λ, G)
```

```julia
svk =  SVK(λ, G)
```
look good to me, so the variable name doesn't shadow the struct name.

Also label names `"svkHyper"` seem fine to me as well.

**Comment by mvanzulli** [comment]
Okay, but is not renamed yet to `Svk` right?  Maybe this issue is just a subitem in #387
