### ISSUE TITLE
Reorganize old files and update them to the new interface version

### ISSUE THREAD

**Issue by mvanzulli** [mvanzulli/ONSAS.jl#47]
Obviously old files and valuable contributions form @jorgepz  and @JoaquinViera  will be included from [this commit](https://github.com/ONSAS/ONSAS.jl/tree/63f37ffb9eab0a7e970b5a81a6a4c9583132fa63)  to solve canonical problems with the "new" interface.

Together with @mforets we think that by the moment (for the sake of clarity) is better to include only files that are being used. Are u agree ?

**Comment by jorgepz** [comment]
Now that there are more than two active developers, we should set a meeting, maybe via gitter, to openly discuss these issues.

**Comment by mvanzulli** [comment]
Closed via #49
