### ISSUE TITLE
Set author/contributor policies

### ISSUE THREAD

**Issue by jorgepz** [mvanzulli/ONSAS.jl#48]
Discuss and define a author/contributor policy in a md file.

**Comment by mvanzulli** [comment]
A Contributing.MD has been added in #130

**Comment by mforets** [comment]
Given the nice writeup https://github.com/ONSAS/ONSAS.jl/blob/main/CONTRIBUTING.md , should we close this?

**Comment by mvanzulli** [comment]
Agree, closed.
