### ISSUE TITLE
Add constructors inside structs

### ISSUE THREAD

**Issue by mvanzulli** [mvanzulli/ONSAS.jl#5]
This issue seek to add inner constructors for the sake of being more neat. Structs allows to define inner constructors into interface.jl like this: 
```julia
julia> struct OurRational{T<:Integer} <: Real
           num::T
           den::T
           function OurRational{T}(num::T, den::T) where T<:Integer
               if num == 0 && den == 0
                    error("invalid rational: 0//0")
               end
               num = flipsign(num, den)
               den = flipsign(den, den)
               g = gcd(num, den)
               num = div(num, g)
               den = div(den, g)
               new(num, den)
           end
       end
```

**Comment by mvanzulli** [comment]
I will reopen this issue because there is more work to do with different structs and constructor methods

**Comment by jorgepz** [comment]
Perfect! Thanks! If the issue is a task i suggest setting a scope for the task.

**Comment by mvanzulli** [comment]
Since the interface has changed, this issue is no longer useful.
