### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by tkrisnguyen** [mvanzulli/ONSAS.jl#506]
https://github.com/ONSAS/ONSAS.jl/blame/d1ead05e8c0b849a2a5ca75f429aca68253f2af4/src/Entities/Nodes.jl#L99C11-L99C11

please consider to revise as

```
Node(Point(x₁, x₂), dofs)
```

**Comment by mvanzulli** [comment]
> https://github.com/ONSAS/ONSAS.jl/blame/d1ead05e8c0b849a2a5ca75f429aca68253f2af4/src/Entities/Nodes.jl#L99C11-L99C11
> 
> 
> 
> please consider to revise as
> 
> 
> 
> ```
> 
> Node(Point(x₁, x₂), dofs)
> 
> ```

True, thanks for reporting. We can splat that `Tuple`, but the allocation will be done since `SVector` uses it under the hood AFAIK. Feel feee to open a Pull Request 😀

**Comment by mforets** [comment]
xref https://github.com/tkrisnguyen/ONSAS.jl/pull/1
