### ISSUE TITLE
Add progress meter 

### ISSUE THREAD

**Issue by JoaquinViera** [mvanzulli/ONSAS.jl#8]
May be useful in ONSAS.jl @jorgepz 

[Progress meter](https://github.com/timholy/ProgressMeter.jl)

**Comment by jorgepz** [comment]
no doubt!!

**Comment by mvanzulli** [comment]
Since this repo is not currently developed with @jorgepz are reducing the number issues according to our maintenance plan. Thanks @JoaquinViera for submitting this one!
