### ISSUE TITLE
Efficient way to compute element dofs 

### ISSUE THREAD

**Issue by mvanzulli** [mvanzulli/ONSAS.jl#93]
```julia
dofs(e::AbstractElement) = mergewith(vcat, dofs.(nodes(e))...)
"Returns the `AbstractElement` `e` dofs."
function dofs(e::AbstractElement)
    vecdfs = dofs.(nodes(e))
```

- Create a cache with element dofs once the `Mesh` is created.
- Loop over `nodes(e)`

**Comment by mforets** [comment]
This was addressed in https://github.com/ONSAS/ONSAS.jl/pull/363/files , creating an iterator for `dofs` of a mesh.
