### ISSUE TITLE
Add linear dynamic analysis

### ISSUE THREAD

**Issue by mforets** [mvanzulli/ONSAS.jl#98]
Should assemble the matrices M, C, K given a problem formulation like that in https://github.com/ONSAS/ONSAS.jl/issues/97

Can be composed with https://github.com/ONSAS/StructuralDynamicsODESolvers.jl for the dynamic analysis.

**Comment by mvanzulli** [comment]
Pefect, for static cases  we can create a new `LinearGeometricStaticAnalysis` or maybe just `LinearStaticAnalysis` and then if material non linearity is considered we changed the name.  This case can be solved dispatch in _solve like this: 

```julia
"Solves an `LinearStaticAnalysis` `sa` with an AbstractSolver `alg`."
function _solve(sa::LinearStaticAnalysis)

    s = structure(sa)

    states = []

    # load factors iteration 
    while !is_done(sa)

        _apply!(sa, load_bcs(s)) # Compute Fext

        _assemble!(s, sa)

        # Increment U 
          r = residual_forces(c_state)
          K = view(tangent_matrix(c_state), f_dofs_indexes, f_dofs_indexes)
          U = cg(K, r)

          _update!(c_state, U)    

        push!(states, deepcopy(current_state(sa)))

    end

    return states
end
```
For the previous analysis we can keep the same `StaticState` struct with some empty fields. 

I would start for this and then implement a `LinearTransient`  in which we have to implement the `_assemble!(s, sa)` function for inertial forces.

**Comment by mvanzulli** [comment]
If `K` `C` and  `M` are constante the matrices matrix to compute delta u can be cashed at the initial time

**Comment by mvanzulli** [comment]
This issue could be splitted in the folwing tasks:
- [ ] Implement the mass matrices computation for each element. We can start with the LumpedMass Model.
